version: '3.9'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./weblk:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: vuwqqZdf3KBX
      MYSQL_DATABASE: bonusmoney
      MYSQL_USER: graver
      MYSQL_PASSWORD: 96NvKARpP7nB
    ports:
      - "3307:3307"
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql